twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_parameters:
            isInterestDetailsEnabled: '%env(resolve:IS_INTEREST_DETAILS_ENABLED)%'

when@test:
    twig:
        strict_variables: true
    
